server:
  port: 8769
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
turbine:
  clusterNameExpression: "'default'"
  appConfig: edge-server,discovery-server,config-server,simple-micro-service,user-micro-service,document-server
---

spring:
  profiles: docker
server:
  port: 8080
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
turbine:
  clusterNameExpression: "'default'"
  appConfig: edge-server,discovery-server,config-server,simple-micro-service,user-micro-service,document-server


