server:
  port: 8769
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---

spring:
  profiles: docker
server:
  port: 8080
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


